### ISSUE TITLE
docs as part of build

### ISSUE THREAD

**Issue by zenyui** [super-flat/lagom-pb#4]
research how scalapb / lightbend do docs, find a way to publish paradox  (likely into gh pages)

**Comment by Tochemey** [comment]
@zenyui please any update on how to automate the doc deployment?

**Comment by zenyui** [comment]
> @zenyui please any update on how to automate the doc deployment?

Yeah the automation is easy, i'm just trying to figure out why the paradox search is breaking in the gcp storage static site deployment (with the double slash `//`)
