### ISSUE TITLE
Add more information to the readSide event

### ISSUE THREAD

**Issue by Tochemey** [super-flat/lagom-pb#69]
**Is your feature request related to a problem? Please describe.**
At the moment the readSide handlers only return the actual event which is good. However the event envelope offered by Akka Projection provide more additional details like the persistenceId the timestamp, the sequenceNumber that can help.

**Describe the solution you'd like**
Expose the persistenceId and the timestamp as well as the sequenceNumber.
Create a proto message for readSide event and make exportable by any application.

**Describe alternatives you've considered**
No

**Additional context**
No.

**Comment by Tochemey** [comment]
For now we will wait for the new release of akka projections and probably of lagom and see how best to tackle this.

**Comment by zenyui** [comment]
@Tochemey let's close this

**Comment by Tochemey** [comment]
This issue is now necessary
